apiVersion: batch/v1
kind: Job
metadata:
  name: argo-pre-sync
  namespace: argocd
  annotations:
     argocd.argoproj.io/hook: PreSync
     argocd.argoproj.io/hook-delete-policy: HookSucceeded, HookFailed
spec:
  backoffLimit: 1
  template:
    spec:
      initContainers:
      - name: git-clone
        image: alpine/git
        command: ["sh", "-c"]
        args:
        - git clone https://github.com/aromalsb/learning.git /repo && cd /repo/sai/ocp-sai-g1
        volumeMounts:
        - name: repo-volume
          mountPath: /repo
      containers:
      - name: kustomize-build
        image: line/kubectl-kustomize
        command: ["sh","-c"]
          # If the previous command fails (non-zero exit code), this triggers the block of commands in {}.
          # { echo ...; exit 1; }:

          # Outputs a custom error message to the console using echo.
          # Exits with a status of 1 to indicate failure.
        args: ["kustomize build /repo/sai/ocp-sai-g1 || { echo 'Error: kustomize build failed. Please check your configuration.'; exit 1; }"]
        # command: ["sleep"]
        # args: ["infinity"]
        volumeMounts:
        - name: repo-volume
          mountPath: /repo
      volumes:
      - name: repo-volume
        emptyDir: {}
      restartPolicy: Never